//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETong.Coffee.Api.Logc.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BM_COFFEE_DETAIL
    {
        public string ID { get; set; }
        public string ORDER_ID { get; set; }
        public string COFFEE_TYPE { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> ADD_FEE { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> RUN_STATUS { get; set; }
        public string COFFEE_TYPENAME { get; set; }
        public Nullable<decimal> CAPACITY { get; set; }
        public string MATERIALS { get; set; }
        public Nullable<int> ISSUED { get; set; }
    }
}
