//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETong.Coffee.Api.Logc.EntityModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoffeeOrderContext : DbContext
    {
        public CoffeeOrderContext()
            : base("name=CoffeeOrderContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BM_COFFEE_DETAIL> BM_COFFEE_DETAIL { get; set; }
        public virtual DbSet<PUB_ORDER> PUB_ORDER { get; set; }
    }
}
