//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETong.Coffee.Api.Logc.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETM_BIZ_AGENT_DEALER_DRIVER
    {
        public string DRIVER_ID { get; set; }
        public Nullable<decimal> DRIVER_TYPE { get; set; }
        public string AGENT_ID { get; set; }
        public string DEALER_ID { get; set; }
        public Nullable<decimal> PROPERTY_TYPE { get; set; }
        public Nullable<System.DateTime> PROPERTY_DATE { get; set; }
        public string DRIVER_IP { get; set; }
        public string DRIVER_CODE { get; set; }
        public Nullable<bool> ACTIVE_STATE { get; set; }
        public string ACTIVE_BY { get; set; }
        public Nullable<System.DateTime> ACTIVE_DATE { get; set; }
        public string SETUP_BY { get; set; }
        public Nullable<System.DateTime> SETUP_DATE { get; set; }
        public Nullable<System.DateTime> LAST_REPORT_DATE { get; set; }
        public Nullable<decimal> DRIVER_STATE { get; set; }
        public string ADDRESS_PROVINCE { get; set; }
        public string ADDRESS_CITY { get; set; }
        public string ADDRESS_AREA { get; set; }
        public string ADDRESS_PATH { get; set; }
        public string ADDRESS_LOCATION { get; set; }
        public string ADDRESS_MAP_GIS { get; set; }
        public string CIRCUMFERENCE_NOTE { get; set; }
        public string REMARK { get; set; }
        public string MEMBER_ID { get; set; }
        public string LOCATION_ID { get; set; }
        public Nullable<decimal> LONGITUDE { get; set; }
        public Nullable<decimal> LATITUDE { get; set; }
        public string CONTACT_MOBILE { get; set; }
        public string STORE_NAME { get; set; }
        public string CHANNEL_GROUP_ID { get; set; }
        public string SERVICE_GROUP_ID { get; set; }
    }
}
