//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETong.Coffee.Api.Logc.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUB_ORDER
    {
        public string ORDER_ID { get; set; }
        public bool IS_DELETE { get; set; }
        public Nullable<bool> IS_CREDIT { get; set; }
        public byte ORDER_STATUS { get; set; }
        public Nullable<byte> ORDER_SUB_STATUS { get; set; }
        public int ORDER_FROM { get; set; }
        public int ORDER_TYPE { get; set; }
        public bool ORDER_CLASSIFY { get; set; }
        public decimal TOTAL_AMOUNT { get; set; }
        public int PAYMENT_STATUS { get; set; }
        public Nullable<System.DateTime> PAYMENT_DATE { get; set; }
        public string PAY_ETM { get; set; }
        public string ORDER_ETM { get; set; }
        public string MEMBER_ID { get; set; }
        public string MEMBER_NAME { get; set; }
        public string CREATOR_IP { get; set; }
        public string STORE_ID { get; set; }
        public string STORE_NAME { get; set; }
        public string IMG_URL { get; set; }
        public string GOODS_URL { get; set; }
        public string PRODUCT_DESC { get; set; }
        public byte ALLOCATION_STATUS { get; set; }
        public Nullable<decimal> ORDER_AMOUNT { get; set; }
        public Nullable<decimal> DELIVERY_FEE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime MODIFY_DATE { get; set; }
        public string INST_ID { get; set; }
        public string PAYMENT_BATCH_NO { get; set; }
        public byte PAYMENT_TYPE { get; set; }
        public string PAYMENT_ORDER_ID { get; set; }
        public string PAYMENT_ACCOUNT_ID { get; set; }
        public string MESSAGE { get; set; }
        public string STORE_TEL { get; set; }
        public string DETIAL_JSON_TEXT { get; set; }
        public string PROVIDER_ID { get; set; }
        public string ORDER_DESC { get; set; }
        public string RATE_ID { get; set; }
        public Nullable<System.DateTime> ORDER_FINISH_DATE { get; set; }
        public string FREIGHT_TEMPLATE_ID { get; set; }
        public string FREIGHT_TYPE_ID { get; set; }
        public string FREIGHT_TYPE_NAME { get; set; }
        public string ORDER_PROPERTIES { get; set; }
    }
}
