//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETong.ETM.Sdk.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETM_LOCATION_TO_LOCATION
    {
        public string LOCATION_TO_LOCATION_ID { get; set; }
        public string LOCATION_ID { get; set; }
        public byte API_TYPE { get; set; }
        public string API_LOCATION_ID { get; set; }
        public string API_LOCATION_NAME { get; set; }
        public string API_LOCATION_BIZTYPE { get; set; }
        public Nullable<System.DateTime> GMT_CREATE { get; set; }
        public Nullable<System.DateTime> GMT_MODIFY { get; set; }
        public string API_LOCATION_DEFAULT { get; set; }
        public string API_LOCATION_PARENTID { get; set; }
    }
}
