//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JavaOrderSdk.Members
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBER
    {
        public string MEMBER_ID { get; set; }
        public string EMAIL { get; set; }
        public string USERNAME { get; set; }
        public string MOBILE { get; set; }
        public string PASSWD { get; set; }
        public Nullable<bool> STATE { get; set; }
        public Nullable<bool> ACTIVATE { get; set; }
        public Nullable<bool> TYP { get; set; }
        public Nullable<bool> REG_FROM { get; set; }
        public string REG_IP { get; set; }
        public string FEATURE { get; set; }
        public Nullable<System.DateTime> GMT_REG { get; set; }
        public Nullable<System.DateTime> GMT_MODIFY { get; set; }
        public string LEVEL_ID { get; set; }
        public Nullable<int> WEB_TOTAL { get; set; }
        public Nullable<int> APP_TOTAL { get; set; }
        public Nullable<int> ETM_TOTAL { get; set; }
        public Nullable<int> LOGIN_NUMBER { get; set; }
        public Nullable<System.DateTime> GMT_LOGIN { get; set; }
        public string LOGIN_IP { get; set; }
        public string P_ID { get; set; }
        public string BIND_MOBILE { get; set; }
        public string BIND_EMAIL { get; set; }
        public string DRIVER_ID { get; set; }
        public Nullable<decimal> RECOMMEND_CODE { get; set; }
    }
}
