//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NativeOrderSdk.Common.EntityModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class PUB_ORDERS_EXTENDED
    {
        [Key]
        public string ORDER_ID { get; set; }
        public short ORDER_TYPE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string INST_ID { get; set; }
        public string CONTENT { get; set; }
        public string EXTCOL01 { get; set; }
        public string EXTCOL02 { get; set; }
        public string EXTCOL03 { get; set; }
        public string EXTCOL04 { get; set; }
        public string EXTCOL05 { get; set; }
        public string EXTCOL06 { get; set; }
        public string EXTCOL07 { get; set; }
        public string EXTCOL08 { get; set; }
        public string EXTCOL09 { get; set; }
        public string EXTCOL10 { get; set; }
        public string EXTCOL11 { get; set; }
        public string EXTCOL12 { get; set; }
        public string EXTCOL13 { get; set; }
        public string EXTCOL14 { get; set; }
        public string EXTCOL15 { get; set; }
        public string EXTCOL16 { get; set; }
        public string EXTCOL17 { get; set; }
        public string EXTCOL18 { get; set; }
        public string EXTCOL19 { get; set; }
        public string EXTCOL20 { get; set; }
        public string EXTCOL21 { get; set; }
        public string EXTCOL22 { get; set; }
        public string EXTCOL23 { get; set; }
        public string EXTCOL24 { get; set; }
        public string EXTCOL25 { get; set; }
        public string EXTCOL26 { get; set; }
        public string EXTCOL27 { get; set; }
        public string EXTCOL28 { get; set; }
        public string EXTCOL29 { get; set; }
        public string EXTCOL30 { get; set; }
        public string EXTCOL31 { get; set; }
        public string EXTCOL32 { get; set; }
        public string EXTCOL33 { get; set; }
        public string EXTCOL34 { get; set; }
        public string EXTCOL35 { get; set; }
        public string EXTCOL36 { get; set; }
        public string EXTCOL37 { get; set; }
        public string EXTCOL38 { get; set; }
        public string EXTCOL39 { get; set; }
        public string EXTCOL40 { get; set; }
        public string EXTCOL41 { get; set; }
        public string EXTCOL42 { get; set; }
        public string EXTCOL43 { get; set; }
        public string EXTCOL44 { get; set; }
        public string EXTCOL45 { get; set; }
        public string EXTCOL46 { get; set; }
        public string EXTCOL47 { get; set; }
        public string EXTCOL48 { get; set; }
        public string EXTCOL49 { get; set; }
        public string EXTCOL50 { get; set; }
        public string BIGCOL01 { get; set; }
        public string BIGCOL02 { get; set; }
        public string BIGCOL03 { get; set; }
        public string BIGCOL04 { get; set; }
        public string BIGCOL05 { get; set; }
        [ForeignKey("ORDER_ID")]
        public virtual PUB_ORDERS_COMMON PUB_ORDERS_COMMON { get; set; }
    }
}
