//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NativeOrderSdk.Common.EntityModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PUB_ORDERS_GROUP
    {
        public PUB_ORDERS_GROUP()
        {
            this.PUB_ORDERS_COMMON = new HashSet<PUB_ORDERS_COMMON>();
        }
        [Key]
        public string ORDER_GROUP_ID { get; set; }
        public Nullable<short> IS_CREDIT { get; set; }
        public Nullable<short> ORDER_TYPE { get; set; }
        public Nullable<long> TOTAL_ORDERS { get; set; }
        public Nullable<decimal> TOTAL_AMOUNT { get; set; }
        public string MEMBER_ID { get; set; }
        public string STORE_ID { get; set; }
        public string STORE_NAME { get; set; }
        public System.DateTime ORDER_DATE { get; set; }
        public string INST_ID { get; set; }

        public virtual ICollection<PUB_ORDERS_COMMON> PUB_ORDERS_COMMON { get; set; }
    }
}
